### ISSUE TITLE
Time extension

### ISSUE THREAD

**Issue by MITEL-UNIUD** [drivendataorg/snomed-ct-entity-linking-runtime#16]
Hi, with our last submission we encurred in "Your submission timed out after running for too long on the execution platform. Reduce your runtime to the maximum allowed duration and try again." . In the web site it is suggested to open an issue here. 
Since it is the last day, can we have an extension of the running time? In the meantime we try to optimize, thanks.

**Comment by chrisjkuch** [comment]
Hey @MITEL-UNIUD-

The 1-hour inference time limit is a resource constraint on competition solutions and will not be extended. You should optimize your solution so that it completes in the allotted time.
