### ISSUE TITLE
Add SciSpacy to runtime

### ISSUE THREAD

**Issue by profliuhao** [drivendataorg/snomed-ct-entity-linking-runtime#8]
Can you consider adding scispacy==0.5.3 to the run time? ScispaCy is a Python package containing spaCy models for processing biomedical, scientific or clinical text. It is a better fit for this task than spaCy.

**Comment by chrisjkuch** [comment]
@profliuhao scispacy has been added and the images are building now, will be pushed and available via the container registry shortly. 

If you have additional packages you would like to have available, please consider submitting a pull request to add them - it will be faster and easier, as we cannot guarantee that we can quickly respond to or fulfill all requests.

**Comment by chrisjkuch** [comment]
Yes, you should include such models in your submission.
